# This workflow will install Python dependencies, build the data with RDFox and build the jupyter-book

name: Build

on:
  push:
    branches: [ master, github_actions ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.config.os }}

    strategy:
      matrix:
        python-version: [3.11]
        config:
          - os: ubuntu-latest

    defaults:
      # Needed for conda environment (https://github.com/marketplace/actions/setup-miniconda#use-a-default-shell)
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v4
    - name: Cache conda
      uses: actions/cache@v3
      env:
        # Increase this value to reset cache if environment.yml has not changed
        CACHE_NUMBER: 0
      with:
        path: ~/conda_pkgs_dir
        key:
          ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment.yml') }}
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: probs-module-data-conversion
        environment-file: environment.yml
        python-version:  ${{ matrix.python-version }}
        auto-activate-base: false
        # use-only-tar-bz2: true # IMPORTANT: This needs to be set for caching to work properly
    - name: Convert ontology
      run: |
        cd conversion
        python convert_ontology.py additional_ontologies/*
        python -m build
      env:
        RDFOX_LICENSE_CONTENT: ${{ secrets.RDFOX_LICENSE }}
    - name: Build documentation
      run: |
        jupyter-book build docs

    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build/html
